### ISSUE TITLE
Dockerize Application, and spin up together with a Redis instance into a docker-compose

### ISSUE THREAD

**Issue by tenongene** [tenongene/visitor-count-app#5]

**Comment by tenongene** [comment]
```

version: "3.9"
services: 
  web:
    build: .
    ports:
      - 7575:7575
    depends_on:
      - db

  db:
    image: "redis:7-alpine"
    ports: 
      - 6379:6379
    restart: always
    volumes:
      - ./data:/data
    command: ["redis-server", "--save 60 1", "--loglevel warning"]

```


=======================================

- Docker-compose.yaml file to spin up both containers.
- Will be on the same network automatically.
- Mapped a local volume to save data from redis container in the event the container crashes.


--------------------------



![Image](https://user-images.githubusercontent.com/49034904/214475090-d43f9964-b83c-4185-810b-8eccaa3c01e2.png)



- Docker containers have a built-in DNS server  and containers can be resolved by their hostname.
- Thus refactoring connection code snippet to reach the redis db container with the **_"db"_** name defined in the docker-compose file
