### ISSUE TITLE
Project Extension: Configure a GitLab CI pipeline to build and push docker image

### ISSUE THREAD

**Issue by tenongene** [tenongene/visitor-count-app#6]

**Comment by tenongene** [comment]
Pushed project into a repository in GitLab.


```
stages:
- test
- build
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
 
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile


```


 - Configured a ".gitlab-ci.yaml" file for continuous integration.
 - Defined environment variables in pipeline for Login to docker registry.




![Image](https://user-images.githubusercontent.com/49034904/214476626-b5f88430-bd0e-4e0b-b8ee-660552f0e174.png)
